[project]
dependencies = [
  "bs4>=0.0.2",
  "google-genai>=0.8.0",
  "python-dotenv>=1.0.1",
  "selenium>=4.28.1",
]
description = "Webscrapping from TabNine"
name = "issues-web-scrapping"
readme = "README.md"
requires-python = ">=3.13"
version = "0.1.0"
